Normalize data
OleguerCanal/signatures-net pull request #4
Opened 2021-05-03 15:25 UTC by cserranocolome

Included the file with the functions to normalize real data. 
I have also included this in the signature_net file (the one that runs everything) and I included the models, that were not included yet. Check this, please.

2021-05-03 22:17 UTC, OleguerCanal requested changes

2021-05-03 22:17 UTC, OleguerCanal commented on src/models/signature_net.py
> +        self.finetuner.load_state_dict(torch.load(os.path.join("../../trained_models", experiment_id_finetune), map_location=torch.device('cpu')))
model path and name to lead should be not be hardcoded, could you do it an argument?

2021-05-03 22:17 UTC, OleguerCanal commented on src/models/signature_net.py
> +        self.error_finder.load_state_dict(torch.load(os.path.join("../../trained_models", experiment_id_error_finder), map_location=torch.device('cpu')))
same

2021-05-03 22:17 UTC, OleguerCanal commented on src/models/signature_net.py
> +        opp = create_opportunities(path_opportunities)
this could be initialized in __init__, no need to reload it again each time we want to find the signature decomposition of a mutation

2021-05-03 22:17 UTC, OleguerCanal commented on src/models/signature_net.py
> +        normalized_mutation_vec = normalize_data(mutation_vec, opp)
nice :+1:

2021-05-03 22:17 UTC, OleguerCanal commented on src/tests/model_tester.py
> +
I'm a bit confused by this:, isn't this what the class SignatureNet is supposed to be doing?

2021-05-03 22:17 UTC, OleguerCanal commented on src/train_errorfinder.py
> +    finetuner.load_state_dict(torch.load(os.path.join(model_path, finetuner_model_name), map_location=torch.device('cpu')))
Nice! :+1:

2021-05-04 08:29 UTC, cserranocolome commented on src/models/signature_net.py
> +        opp = create_opportunities(path_opportunities)
I agree. Done

2021-05-04 08:31 UTC, cserranocolome commented on src/tests/model_tester.py
> +
Yes. This is an outdated file that I reused to do a quick check. This is from the previous version.

2021-05-04 08:53 UTC, OleguerCanal commented on src/tests/model_tester.py
> +
:+1:

2021-05-04 08:54 UTC, OleguerCanal approved these changes

2021-05-04 08:56 UTC, merged